### ISSUE TITLE
Redis timeout error

### ISSUE THREAD

**Issue by afandian** [CrossRef/event-data-live-demo#3]
`
  [async-thread-macro-1] INFO event-data-live-demo.core - Broadcast to  1
  [async-thread-macro-1] INFO event-data-live-demo.core - Broadcast to  1
  [async-thread-macro-1] INFO event-data-live-demo.core - Broadcast to  1
  [async-thread-macro-1] INFO event-data-live-demo.core - Broadcast to  1
  Thu Dec 22 09:00:01 GMT 2016 [worker-1] ERROR - POST /events
  redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Operation timed out
   at redis.clients.jedis.Connection.flush(Connection.java:291)
   at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:194)
   at redis.clients.jedis.BinaryJedis.select(BinaryJedis.java:432)
   at event_data_common.storage.redis$get_connection.invoke(redis.clj:41)
   at event_data_common.storage.redis.RedisConnection.publish_pubsub(redis.clj:104)
   at event_data_live_demo.core$events$fn__12951$fn__12954.invoke(core.clj:60)
   at liberator.core$decide.invoke(core.clj:81)
   at liberator.core$post_BANG_.invoke(core.clj:241)
...
   at liberator.core$decide.invoke(core.clj:86)
   at liberator.core$initialize_context.invoke(core.clj:493)
   at liberator.core$run_resource.invoke(core.clj:581)
   at event_data_live_demo.core$events$fn__12951.invoke(core.clj:49)
   at compojure.response$eval909$fn__910.invoke(response.clj:33)
   at compojure.response$eval864$fn__865$G__855__872.invoke(response.clj:6)
   at compojure.core$make_route$fn__2518.invoke(core.clj:135)
   at compojure.core$wrap_route_middleware$fn__2511.invoke(core.clj:122)
   at compojure.core$wrap_route_info$fn__2515.invoke(core.clj:126)
   at compojure.core$if_route$fn__2469.invoke(core.clj:45)
   at compojure.core$if_method$fn__2459.invoke(core.clj:27)
   at compojure.core$routing$fn__2525.invoke(core.clj:151)
   at clojure.core$some.invoke(core.clj:2570)
   at compojure.core$routing.doInvoke(core.clj:151)
   at clojure.lang.RestFn.applyTo(RestFn.java:139)
   at clojure.core$apply.invoke(core.clj:632)
   at compojure.core$routes$fn__2529.invoke(core.clj:156)
   at ring.middleware.params$wrap_params$fn__2699.invoke(params.clj:64)
   at event_data_common.jwt$wrap_jwt$fn__4907.invoke(jwt.clj:67)
   at ring.middleware.resource$wrap_resource$fn__12929.invoke(resource.clj:28)
   at ring.middleware.content_type$wrap_content_type$fn__2718.invoke(content_type.clj:30)
   at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
   at java.util.concurrent.FutureTask.run(FutureTask.java:266)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
  Caused by: java.net.SocketException: Operation timed out
   at java.net.SocketOutputStream.socketWrite0(Native Method)
   at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
   at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
   at redis.clients.util.RedisOutputStream.flushBuffer(RedisOutputStream.java:31)
   at redis.clients.util.RedisOutputStream.flush(RedisOutputStream.java:213)
   at redis.clients.jedis.Connection.flush(Connection.java:288)
   ... 84 more
`

**Comment by afandian** [comment]
https://github.com/xetorthio/jedis/wiki/FAQ
